/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ejercicio_files;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.StringTokenizer;
import javax.swing.ImageIcon;

/**
 *
 * @author xxjfg
 */
public class Ventana extends javax.swing.JFrame {
    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        background = new javax.swing.JPanel();
        mostrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        texto = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();
        nombre = new javax.swing.JCheckBox();
        apellido1 = new javax.swing.JCheckBox();
        apellido2 = new javax.swing.JCheckBox();
        dia_mes = new javax.swing.JCheckBox();
        año = new javax.swing.JCheckBox();
        def = new javax.swing.JCheckBox();
        car = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Files");
        setIconImage(new ImageIcon(getClass().getResource("/Recursos/icono.png")).getImage());
        setMaximumSize(null);
        setMinimumSize(null);
        setName("frame"); // NOI18N
        setSize(new java.awt.Dimension(400, 500));
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(153, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LECTOR DE ARCHIVO");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 460, 50);

        jPanel1.setBackground(new java.awt.Color(204, 0, 0));
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 50, 460, 10);

        jPanel2.setBackground(new java.awt.Color(255, 0, 0));
        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 60, 460, 10);

        jPanel3.setBackground(new java.awt.Color(255, 102, 102));
        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 70, 460, 10);

        jPanel4.setBackground(new java.awt.Color(153, 0, 0));
        getContentPane().add(jPanel4);
        jPanel4.setBounds(0, 470, 460, 30);

        background.setBackground(new java.awt.Color(255, 204, 204));
        background.setLayout(null);

        mostrar.setBackground(new java.awt.Color(255, 102, 102));
        mostrar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        mostrar.setForeground(new java.awt.Color(255, 255, 255));
        mostrar.setText("Mostrar");
        mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarActionPerformed(evt);
            }
        });
        background.add(mostrar);
        mostrar.setBounds(200, 430, 240, 27);

        texto.setEditable(false);
        texto.setBackground(new java.awt.Color(255, 241, 241));
        jScrollPane1.setViewportView(texto);

        background.add(jScrollPane1);
        jScrollPane1.setBounds(200, 100, 240, 320);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Parámetros que \nmostrar:");
        background.add(jLabel2);
        jLabel2.setBounds(10, 130, 170, 30);

        nombre.setBackground(new java.awt.Color(255, 204, 204));
        nombre.setText("Nombre");
        background.add(nombre);
        nombre.setBounds(20, 170, 80, 20);

        apellido1.setBackground(new java.awt.Color(255, 204, 204));
        apellido1.setText("1er Apellido");
        background.add(apellido1);
        apellido1.setBounds(20, 190, 100, 20);

        apellido2.setBackground(new java.awt.Color(255, 204, 204));
        apellido2.setText("2do Apellido");
        background.add(apellido2);
        apellido2.setBounds(20, 210, 100, 20);

        dia_mes.setBackground(new java.awt.Color(255, 204, 204));
        dia_mes.setText("Día y mes de nacimiento");
        background.add(dia_mes);
        dia_mes.setBounds(20, 230, 170, 20);

        año.setBackground(new java.awt.Color(255, 204, 204));
        año.setText("Año de nacimiento");
        background.add(año);
        año.setBounds(20, 250, 130, 20);

        def.setBackground(new java.awt.Color(255, 204, 204));
        def.setText("Default");
        def.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                defActionPerformed(evt);
            }
        });
        background.add(def);
        def.setBounds(20, 270, 120, 20);

        car.setBackground(new java.awt.Color(255, 204, 204));
        car.setSelected(true);
        car.setText("Primer caracter");
        background.add(car);
        car.setBounds(20, 360, 170, 20);

        getContentPane().add(background);
        background.setBounds(0, 0, 460, 500);

        setSize(new java.awt.Dimension(471, 508));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarActionPerformed
        String line, token;
        String nom = null, ap1 = null, ap2 = null, d = null, m = null, a = null, pal="";
        StringTokenizer tokenizer;
        int cuenta_token;
        try {
            FileReader file = new FileReader("src/Recursos/data.txt");
            BufferedReader br = new BufferedReader(file);
            
            texto.setText("");
            line = br.readLine();
            while (line != null) {
                cuenta_token = 0;
                tokenizer = new StringTokenizer(line, ",");
                pal = "";
                while (tokenizer.hasMoreTokens()) {
                    token = tokenizer.nextToken();
                    cuenta_token++;
                    pal += token.substring(0, 1);
                    if(!def.isSelected())
                    {
                        switch(cuenta_token)
                        {
                            case 1:
                                if(nombre.isSelected())
                                    texto.setText(texto.getText() + token + " ");
                                break;
                            case 2:
                                if(apellido1.isSelected())
                                    texto.setText(texto.getText() + token + " ");
                                break;
                            case 3:
                                if(apellido2.isSelected())
                                    texto.setText(texto.getText() + token + " ");
                                break;
                            case 4:
                                if(dia_mes.isSelected())
                                {
                                    texto.setText(texto.getText() + token + "/" + tokenizer.nextToken());
                                    cuenta_token++;
                                }
                                break;
                            case 6:
                                if(dia_mes.isSelected() && año.isSelected())
                                    texto.setText(texto.getText() + "/");
                                if(año.isSelected())
                                    texto.setText(texto.getText() + token);
                                break;
                        }
                    }
                }
                if(def.isSelected())
                {
                    texto.setText(texto.getText() + line);
                }
                if(car.isSelected())
                {
                    texto.setText(texto.getText() + "  " + pal);
                }
                texto.setText(texto.getText() + "\r\n");
                line = br.readLine();
            }

            file.close();
        } catch (IOException e) {
            System.out.println("Exception");
        }
    }//GEN-LAST:event_mostrarActionPerformed

    private void defActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_defActionPerformed
        if(def.isSelected())
        {
            nombre.setEnabled(false);apellido1.setEnabled(false);apellido2.setEnabled(false);
            dia_mes.setEnabled(false);año.setEnabled(false);
        }else
        {
            nombre.setEnabled(true);apellido1.setEnabled(true);apellido2.setEnabled(true);
            dia_mes.setEnabled(true);año.setEnabled(true);
        }
    }//GEN-LAST:event_defActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox apellido1;
    private javax.swing.JCheckBox apellido2;
    private javax.swing.JCheckBox año;
    private javax.swing.JPanel background;
    private javax.swing.JCheckBox car;
    private javax.swing.JCheckBox def;
    private javax.swing.JCheckBox dia_mes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton mostrar;
    private javax.swing.JCheckBox nombre;
    private javax.swing.JTextPane texto;
    // End of variables declaration//GEN-END:variables
}
