/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ejercicio_u2;

import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author xxjfg
 */
public final class Ventana extends javax.swing.JFrame {
    String[] flecha = {"derecha", "izquierda", "arriba_abajo"};
    int n, ac = 0;
    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
        flechaAleatoria();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        aciertos = new javax.swing.JLabel();
        imagen = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        btnIzq = new javax.swing.JButton();
        btnNin = new javax.swing.JButton();
        btnDer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Flechas");
        setBackground(new java.awt.Color(255, 255, 255));
        setIconImage(new ImageIcon(getClass().getResource("/Recursos/icono.png")).getImage());
        setMinimumSize(new java.awt.Dimension(450, 450));
        setPreferredSize(new java.awt.Dimension(450, 450));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setMinimumSize(new java.awt.Dimension(450, 450));
        jPanel1.setName(""); // NOI18N
        jPanel1.setLayout(null);

        aciertos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        aciertos.setForeground(new java.awt.Color(153, 153, 153));
        aciertos.setText("0");
        jPanel1.add(aciertos);
        aciertos.setBounds(380, 400, 40, 50);

        imagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/arriba_abajo.png"))); // NOI18N
        jPanel1.add(imagen);
        imagen.setBounds(20, 80, 410, 190);

        lbl1.setBackground(new java.awt.Color(0, 0, 0));
        lbl1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl1.setForeground(new java.awt.Color(255, 255, 255));
        lbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl1.setText("Ingresa la flecha mostrada:");
        lbl1.setOpaque(true);
        jPanel1.add(lbl1);
        lbl1.setBounds(0, 0, 450, 50);

        lbl2.setBackground(new java.awt.Color(0, 0, 0));
        lbl2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl2.setForeground(new java.awt.Color(255, 255, 255));
        lbl2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbl2.setText("Aciertos:                 ");
        lbl2.setToolTipText("");
        lbl2.setOpaque(true);
        jPanel1.add(lbl2);
        lbl2.setBounds(0, 400, 450, 50);

        btnIzq.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnIzq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/btnIzq.png"))); // NOI18N
        btnIzq.setToolTipText("");
        btnIzq.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnIzq.setName("izquierda"); // NOI18N
        btnIzq.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPressed(evt);
            }
        });
        jPanel1.add(btnIzq);
        btnIzq.setBounds(20, 320, 130, 60);

        btnNin.setBackground(new java.awt.Color(255, 255, 254));
        btnNin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnNin.setText("Ninguno");
        btnNin.setToolTipText("");
        btnNin.setActionCommand("");
        btnNin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnNin.setName("arriba_abajo"); // NOI18N
        btnNin.setOpaque(true);
        btnNin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPressed(evt);
            }
        });
        jPanel1.add(btnNin);
        btnNin.setBounds(160, 320, 130, 60);

        btnDer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/btnDer.png"))); // NOI18N
        btnDer.setToolTipText("");
        btnDer.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnDer.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnDer.setName("derecha"); // NOI18N
        btnDer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPressed(evt);
            }
        });
        jPanel1.add(btnDer);
        btnDer.setBounds(300, 320, 130, 60);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 450, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPressed
        JButton btn = (JButton) evt.getSource();
        if(btn.getName().equalsIgnoreCase(flecha[n]))
        {
            ac++;
            aciertos.setText(Integer.toString(ac));
            if(ac==10)
            {
                JOptionPane.showMessageDialog(null, "Has acertado 10 veces.", "Flechas", JOptionPane.INFORMATION_MESSAGE);
                btnDer.setEnabled(false);
                btnIzq.setEnabled(false);
                btnNin.setEnabled(false);
                return;
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Te equivocaste", "Flechas", JOptionPane.INFORMATION_MESSAGE);
        }
        flechaAleatoria();
    }//GEN-LAST:event_btnPressed
    
    void flechaAleatoria()
    {
        Random random = new Random();
        n = random.nextInt(3);
        imagen.setIcon(new ImageIcon(getClass().getResource("/Recursos/"+ flecha[n] +".png")));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aciertos;
    private javax.swing.JButton btnDer;
    private javax.swing.JButton btnIzq;
    private javax.swing.JButton btnNin;
    private javax.swing.JLabel imagen;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    // End of variables declaration//GEN-END:variables
}
