/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Main.java to edit this template
 */
package ejercicio_dibujo;

import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

import java.awt.Graphics;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author xxjfg
 */
public class Ejercicio_Dibujo extends javax.swing.JFrame {
    int c = 0;

    class Panel extends JPanel {
        
        private void dibujar(Graphics g, int i)
        {
            for(i= 0; i <= c; i++) {
                switch (i) {
                    case 1:
                        g.setColor(new Color(0, 87, 0));
                        g.fillRect(0, panel.getHeight() - 150, panel.getWidth(), 150);
                        break;
                    case 2:
                        g.setColor(new Color(255, 197, 0));
                        g.fillOval(20, 20, 50, 50);
                        break;
                    case 3:
                        g.setColor(new Color(222, 201, 89));
                        g.fillRect(70, 185, 115, 115);
                        g.setColor(new Color(164, 150, 69));
                        g.fillPolygon(new int[]{185, 290, 290, 185}, new int[]{300, 245, 130, 185}, 4);
                        break;
                    case 4:
                        g.setColor(new Color(218, 115, 34));
                        g.fillPolygon(new int[]{55, 190, 160}, new int[]{195, 195, 100}, 3);
                        g.setColor(new Color(145, 75, 19));
                        g.fillPolygon(new int[]{190, 305, 230, 160}, new int[]{195, 140, 85, 100}, 4);
                        break;
                    case 5:
                        g.setColor(new Color(107, 163, 173));
                        g.fillOval(112, 212, 25, 25);
                        g.setColor(new Color(113, 76, 0));
                        g.fillPolygon(new int[]{230, 260, 260, 230}, new int[]{278, 261, 200, 215}, 4);
                        break;
                    case 6:
                        g.fillRect(420, 180, 25, 120);
                        g.setColor(new Color(143, 211, 74));
                        g.fillOval(420, 120, 60, 100);
                        g.setColor(new Color(68, 137, 0));
                        g.fillOval(407, 75, 50, 130);
                        g.setColor(new Color(108, 175, 42));
                        g.fillOval(380, 110, 65, 110);
                        break;
                    case 7:
                        g.setColor(Color.BLACK);
                        g.setFont(new Font("Segoe UI", Font.PLAIN, 18));
                        g.drawString("Casa estilo \"Cape Rod\"", 190, 40);
                        break;
                }
            }
        }

        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g); // Limpia el fondo del panel
            dibujar(g, c);
        }
    }

    public Ejercicio_Dibujo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        panel = new Panel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dibujo");
        setIconImage(new ImageIcon(getClass().getResource("icon.png")).getImage());
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(212, 235, 250));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ejercicio_dibujo/marco.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 649, 485);

        jButton1.setBackground(new java.awt.Color(102, 51, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Limpiar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(18, 491, 200, 23);

        jButton2.setBackground(new java.awt.Color(102, 51, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Siguiente");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(224, 491, 200, 23);

        jButton3.setBackground(new java.awt.Color(102, 51, 0));
        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Mostrar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(430, 491, 200, 23);

        panel.setBackground(new java.awt.Color(204, 234, 255));

        panel.setLayout(null);

        getContentPane().add(panel);
        panel.setBounds(51, 52, 550, 380);

        setSize(new java.awt.Dimension(665, 558));
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        c=0;
        panel.repaint();
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        if (c < 7) {

            c++;
            panel.repaint();
        }
    }

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
        if (c < 7) {

            c = 7;
            panel.repaint();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio_Dibujo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio_Dibujo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio_Dibujo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio_Dibujo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio_Dibujo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panel;
    // End of variables declaration                   
}
