/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package examenunidadi_jfgr;

import java.awt.Color;
import java.awt.Image;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author xxjfg
 */
public class Juego extends javax.swing.JFrame {
    List<JLabel> casilla = new ArrayList<>(9);
    String player = "O";
    String pc = "X";
    boolean cyx = true;
    boolean terminado = false;
    int[][] gato = new int[3][3];
    /**
     * Creates new form Juego
     */
    public Juego() {
        initComponents();
        ImageIcon img = new ImageIcon(getClass().getResource("/Recursos/fnd.gif"));
        Icon f = new ImageIcon(img.getImage().getScaledInstance(fondo.getWidth(), fondo.getHeight(), Image.SCALE_DEFAULT));
        fondo.setIcon(f);
        this.repaint();
        vaciar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        p11 = new javax.swing.JLabel();
        p12 = new javax.swing.JLabel();
        p13 = new javax.swing.JLabel();
        p21 = new javax.swing.JLabel();
        p22 = new javax.swing.JLabel();
        p23 = new javax.swing.JLabel();
        p31 = new javax.swing.JLabel();
        p32 = new javax.swing.JLabel();
        p33 = new javax.swing.JLabel();
        rOX = new javax.swing.JButton();
        rCol = new javax.swing.JButton();
        simbolo = new javax.swing.JComboBox<>();
        color = new javax.swing.JComboBox<>();
        texto = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Juego de Gato");
        setIconImage(new ImageIcon(getClass().getResource("/Recursos/icono.png")).getImage());
        setMinimumSize(new java.awt.Dimension(550, 823));
        setName("juego"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(550, 800));
        getContentPane().setLayout(null);

        jPanel1.setToolTipText("");
        jPanel1.setMaximumSize(new java.awt.Dimension(550, 700));
        jPanel1.setLayout(null);

        jPanel2.setOpaque(false);
        jPanel2.setLayout(null);

        p11.setBackground(new java.awt.Color(102, 102, 255));
        p11.setName("_11"); // NOI18N
        p11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                seleccion(evt);
            }
        });
        jPanel2.add(p11);
        p11.setBounds(20, 20, 70, 70);

        p12.setBackground(new java.awt.Color(102, 102, 255));
        p12.setName("_12"); // NOI18N
        p12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                seleccion(evt);
            }
        });
        jPanel2.add(p12);
        p12.setBounds(120, 20, 70, 70);

        p13.setBackground(new java.awt.Color(102, 102, 255));
        p13.setName("_13"); // NOI18N
        p13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                seleccion(evt);
            }
        });
        jPanel2.add(p13);
        p13.setBounds(220, 20, 70, 70);

        p21.setBackground(new java.awt.Color(102, 102, 255));
        p21.setName("_21"); // NOI18N
        p21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                seleccion(evt);
            }
        });
        jPanel2.add(p21);
        p21.setBounds(20, 120, 70, 70);

        p22.setBackground(new java.awt.Color(102, 102, 255));
        p22.setName("_22"); // NOI18N
        p22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                seleccion(evt);
            }
        });
        jPanel2.add(p22);
        p22.setBounds(120, 120, 70, 70);

        p23.setBackground(new java.awt.Color(102, 102, 255));
        p23.setName("_23"); // NOI18N
        p23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                seleccion(evt);
            }
        });
        jPanel2.add(p23);
        p23.setBounds(220, 120, 70, 70);

        p31.setBackground(new java.awt.Color(102, 102, 255));
        p31.setName("_31"); // NOI18N
        p31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                seleccion(evt);
            }
        });
        jPanel2.add(p31);
        p31.setBounds(20, 220, 70, 70);

        p32.setBackground(new java.awt.Color(102, 102, 255));
        p32.setName("_32"); // NOI18N
        p32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                seleccion(evt);
            }
        });
        jPanel2.add(p32);
        p32.setBounds(120, 220, 70, 70);

        p33.setBackground(new java.awt.Color(102, 102, 255));
        p33.setName("_33"); // NOI18N
        p33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                seleccion(evt);
            }
        });
        jPanel2.add(p33);
        p33.setBounds(220, 220, 70, 70);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(120, 360, 310, 310);

        rOX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/rXO.png"))); // NOI18N
        rOX.setBorder(null);
        rOX.setBorderPainted(false);
        rOX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rOXActionPerformed(evt);
            }
        });
        jPanel1.add(rOX);
        rOX.setBounds(110, 720, 150, 41);

        rCol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/rCol.png"))); // NOI18N
        rCol.setBorder(null);
        rCol.setBorderPainted(false);
        rCol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rColActionPerformed(evt);
            }
        });
        jPanel1.add(rCol);
        rCol.setBounds(290, 720, 150, 41);

        simbolo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "X", "O" }));
        simbolo.setToolTipText("");
        jPanel1.add(simbolo);
        simbolo.setBounds(470, 30, 50, 22);

        color.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rojo", "Azul", "Verde" }));
        jPanel1.add(color);
        color.setBounds(470, 60, 50, 22);

        texto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        texto.setForeground(new java.awt.Color(255, 204, 255));
        texto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        texto.setText("Modo O y X");
        jPanel1.add(texto);
        texto.setBounds(100, 310, 350, 20);

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/fndAux.png"))); // NOI18N
        jPanel1.add(fondo);
        fondo.setBounds(0, 0, 550, 800);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 550, 800);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private int verificarGanador() {
    int ganador = 0;
    
    for(int i=0; i<3; i++)
        if(gato[i][0] == gato[i][1] && gato[i][1] == gato[i][2] && gato[i][0] > 0)
            ganador = gato[i][0];
    
    for(int i=0; i<3; i++)
        if(gato[0][i] == gato[1][i] && gato[1][i] == gato[2][i] && gato[0][i] > 0)
            ganador = gato[0][i];
    
    if(gato[0][0] == gato[1][1] && gato[1][1] == gato[2][2] && gato[0][0] > 0)
        ganador = gato[0][0];
    
    if(gato[0][2] == gato[1][1] && gato[1][1] == gato[2][0] && gato[0][2] > 0)
        ganador = gato[0][2];
    
    if(ganador == 0)
    {
        ganador = 3;
        for(int i=0;i<3;i++)
            for(int j=0;j<3;j++)
                if(gato[i][j] == 0)
                    ganador = 0;
    }

    return ganador;
}

    void vaciar()
    {
        for(int i=0;i<3;i++)
            for(int j=0;j<3;j++)
                gato[i][j] = 0;
        casilla.clear();
        casilla.add(p11); casilla.add(p12);casilla.add(p13);
        casilla.add(p21); casilla.add(p22);casilla.add(p23);
        casilla.add(p31); casilla.add(p32);casilla.add(p33);
        p11.setOpaque(false);p12.setOpaque(false);p13.setOpaque(false);
        p21.setOpaque(false);p22.setOpaque(false);p23.setOpaque(false);
        p31.setOpaque(false);p32.setOpaque(false);p33.setOpaque(false);
        p11.setIcon(null);p12.setIcon(null);p13.setIcon(null);
        p21.setIcon(null);p22.setIcon(null);p23.setIcon(null);
        p31.setIcon(null);p32.setIcon(null);p33.setIcon(null);
        p11.setEnabled(true);p12.setEnabled(true);p13.setEnabled(true);
        p21.setEnabled(true);p22.setEnabled(true);p23.setEnabled(true);
        p31.setEnabled(true);p32.setEnabled(true);p33.setEnabled(true);
    }
    
    void agregar(JLabel a, String jug)
    {
        switch(a.getName())
        {
            case "_11":
                gato[0][0] = (jug.equalsIgnoreCase(player)? 1:2);
                break;
            case "_12":
                gato[0][1] = (jug.equalsIgnoreCase(player)? 1:2);
                break;
            case "_13":
                gato[0][2] = (jug.equalsIgnoreCase(player)? 1:2);
                break;
            case "_21":
                gato[1][0] = (jug.equalsIgnoreCase(player)? 1:2);
                break;
            case "_22":
                gato[1][1] = (jug.equalsIgnoreCase(player)? 1:2);
                break;
            case "_23":
                gato[1][2] = (jug.equalsIgnoreCase(player)? 1:2);
                break;
            case "_31":
                gato[2][0] = (jug.equalsIgnoreCase(player)? 1:2);
                break;
            case "_32":
                gato[2][1] = (jug.equalsIgnoreCase(player)? 1:2);
                break;
            case "_33":
                gato[2][2] = (jug.equalsIgnoreCase(player)? 1:2);
                break;
        }
    }
    
    void pcJuega()
    {
        Random random = new Random();
        int n = random.nextInt(casilla.size());
        JLabel a = casilla.get(n);
        if(cyx)
        {
            a.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/icon/" + pc + ".png")));
        }else
        {
            a.setBackground(Color.MAGENTA);
            a.setOpaque(true);
        }
        casilla.remove(a);
        agregar(a, pc);
    }
    
    void terminar()
    {
        jPanel2.setEnabled(false);
        terminado = true;
    }
    
    private void seleccion(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seleccion
        JLabel a = (JLabel) evt.getSource();
        
        if(terminado)
            vaciar();
        terminado = false;
        
        if(casilla.contains(a))
        {
            if(cyx)
            {
                a.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/icon/" + player + ".png")));
            }else
            {
                switch(player)
                {
                    case "Rojo":
                        a.setBackground(Color.red);
                        break;
                    case "Azul":
                        a.setBackground(Color.blue);
                        break;
                    case "Verde":
                         a.setBackground(Color.green);
                        break;
                }
                a.setOpaque(true);
            }
            casilla.remove(a);
            agregar(a, player);
            
            int ver = verificarGanador();
            if(ver == 0)
            {
                pcJuega();
                ver = verificarGanador();
            }
            
            if(ver == 1)
            {
                terminar();
                JOptionPane.showMessageDialog(null, "¡¡¡ GANASTE !!!", "Juego de Gato", JOptionPane.INFORMATION_MESSAGE);
            }else if(ver == 2)
            {
                terminar();
                JOptionPane.showMessageDialog(null, "PERDISTE...", "Juego de Gato", JOptionPane.INFORMATION_MESSAGE);
            }else if(ver == 3)
            {
                terminar();
                JOptionPane.showMessageDialog(null, "Empate.", "Juego de Gato", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_seleccion

    private void rOXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rOXActionPerformed
        vaciar();cyx = true;
        player = simbolo.getItemAt(simbolo.getSelectedIndex());
        pc = (player == "X")? "O": "X";
        texto.setText("Modo O y X - Tú eres " + player);
    }//GEN-LAST:event_rOXActionPerformed

    private void rColActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rColActionPerformed
        vaciar();cyx = false;
        player = color.getItemAt(color.getSelectedIndex());
        texto.setText("Modo Colores - Tú eres " + player);
    }//GEN-LAST:event_rColActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Juego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> color;
    private javax.swing.JLabel fondo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel p11;
    private javax.swing.JLabel p12;
    private javax.swing.JLabel p13;
    private javax.swing.JLabel p21;
    private javax.swing.JLabel p22;
    private javax.swing.JLabel p23;
    private javax.swing.JLabel p31;
    private javax.swing.JLabel p32;
    private javax.swing.JLabel p33;
    private javax.swing.JButton rCol;
    private javax.swing.JButton rOX;
    private javax.swing.JComboBox<String> simbolo;
    private javax.swing.JLabel texto;
    // End of variables declaration//GEN-END:variables
}
